GOOGLE_APP_CLIENT_ID: '308790355449-5ra1908iggk09at83tm9t654m5jhe3ot.apps.googleusercontent.com'
GOOGLE_APP_CLIENT_SECRET: 'XekDPx4x8ASAjyhvmBhMoUPS'
FACEBOOK_APP_CLIENT_ID: '481984482657997'
FACEBOOK_APP_CLIENT_SECRET: '46d7c9ea5840fddabdfc7af16079e9f7'
TWITTER_APP_API_KEY: 'BeBoQ727H75xhM5F0Ndgbh7S3'
TWITTER_APP_CLIENT_SECRET: 'jvsnufQU8NCuinDW1sijElm714rjP4e1ywce9Vs3VBRk0IdyyD'
TWITTER_APP_MANAV_ACCESS_TOKEN: '1181816060435021826-luWVBctGrYZg0tFNmUbKvaZXqFxJpl'
TWITTER_APP_MANAV_ACCESS_KEY: 'DVULPiBbA3uUJIlZA7Fsdo26yw7QjOXqpWA0TPl3tRbJD'
API_ACCESS_TOKEN: 'abc'
API_MODIFY_TOKEN: 'ABC'
GOOGLE_APPLICATION_CREDENTIALS: '/home/beryl/Desktop/Training/Training/Rails/college/tmp/College-860beb1f7527.json'
DATABASE_HOST: 'localhost'
DATABASE_PORT: '5432'
DATABASE_USERNAME: 'postgres'
DATABASE_PASSWORD: 'postgres'
DATABASE_DEVELOPMENT: 'college_development'
DATABASE_TEST: 'college_test'
DATABASE_PRODUCTION: 'college'